export const carList = {
    result: [
        {
            id: 'JP2LgGfOu',
            title: 'Toyota Venza',
            imageUrl: 'https://media.autochek.africa/file/gbfZbRMu.webp',
            year: 2010,
            city: 'Okota',
            state: 'Lagos',
            gradeScore: 4.400000095367432,
            sellingCondition: 'foreign',
            hasWarranty: false,
            marketplacePrice: 10915000,
            marketplaceOldPrice: 10915000,
            hasFinancing: true,
            mileage: 11,
            mileageUnit: 'miles',
            installment: 504831,
            depositReceived: false,
            loanValue: 9139485,
            websiteUrl: 'https://autochek.africa/ng/car/venza-toyota-ref-JP2LgGfOu',
            stats: {
                webViewCount: 0,
                webViewerCount: 0,
                interestCount: 0,
                testDriveCount: 0,
                appViewCount: 0,
                appViewerCount: 0,
                processedLoanCount: 0,
            },
            bodyTypeId: '3',
            sold: false,
            hasThreeDImage: false,
            transmission: 'automatic',
            fuelType: 'petrol',
            marketplaceVisibleDate: '2023-10-27T20:45:20.602Z',
        },
        {
            id: 'aL9OpMUnX',
            title: 'Mercedes-Benz E 350',
            imageUrl: 'https://media.autochek.africa/file/3M0wklJH.webp',
            year: 2012,
            city: 'Katampe Road',
            state: 'Abuja',
            gradeScore: 4.400000095367432,
            sellingCondition: 'foreign',
            hasWarranty: false,
            marketplacePrice: 6200000,
            marketplaceOldPrice: 6200000,
            hasFinancing: true,
            mileage: 85799,
            mileageUnit: 'miles',
            installment: 275744,
            depositReceived: false,
            loanValue: 4770722,
            websiteUrl: 'https://autochek.africa/ng/car/e-350-mercedes-benz-ref-aL9OpMUnX',
            stats: {
                webViewCount: 0,
                webViewerCount: 0,
                interestCount: 0,
                testDriveCount: 0,
                appViewCount: 0,
                appViewerCount: 0,
                processedLoanCount: 0,
            },
            bodyTypeId: '8',
            sold: false,
            hasThreeDImage: false,
            transmission: 'automatic',
            fuelType: 'petrol',
            marketplaceVisibleDate: '2023-10-27T16:11:46.679Z',
            ccMeasurement: 1500,
        },
        {
            id: 'RJFePPzpX',
            title: 'Lexus RX 350',
            imageUrl: 'https://media.autochek.africa/file/7qadgRj1.webp',
            year: 2007,
            city: 'Egbeda',
            state: 'Lagos',
            gradeScore: 4.400000095367432,
            sellingCondition: 'foreign',
            hasWarranty: false,
            marketplacePrice: 8715000,
            marketplaceOldPrice: 8715000,
            hasFinancing: true,
            mileage: 234321,
            mileageUnit: 'km',
            installment: 387410,
            depositReceived: false,
            loanValue: 6921186,
            websiteUrl: 'https://autochek.africa/ng/car/rx-350-lexus-ref-RJFePPzpX',
            stats: {
                webViewCount: 0,
                webViewerCount: 0,
                interestCount: 0,
                testDriveCount: 0,
                appViewCount: 0,
                appViewerCount: 0,
                processedLoanCount: 0,
            },
            bodyTypeId: '3',
            sold: false,
            hasThreeDImage: false,
            transmission: 'automatic',
            fuelType: 'petrol',
            marketplaceVisibleDate: '2023-10-26T22:18:56.597Z',
            ccMeasurement: 3500,
        },
        {
            id: '-mpbSsg4H',
            title: 'Lexus RX 350',
            imageUrl: 'https://media.autochek.africa/file/GTuNnnGQ.webp',
            year: 2009,
            city: 'Ejigbo',
            state: 'Lagos',
            gradeScore: 4.400000095367432,
            sellingCondition: 'foreign',
            hasWarranty: false,
            marketplacePrice: 8015000,
            marketplaceOldPrice: 7715000,
            hasFinancing: true,
            mileage: 123321,
            mileageUnit: 'miles',
            installment: 346799,
            depositReceived: false,
            loanValue: 6168608,
            websiteUrl: 'https://autochek.africa/ng/car/rx-350-lexus-ref--mpbSsg4H',
            stats: {
                webViewCount: 0,
                webViewerCount: 0,
                interestCount: 0,
                testDriveCount: 0,
                appViewCount: 0,
                appViewerCount: 0,
                processedLoanCount: 0,
            },
            bodyTypeId: '3',
            sold: false,
            hasThreeDImage: false,
            transmission: 'automatic',
            fuelType: 'petrol',
            marketplaceVisibleDate: '2023-10-27T07:21:30.371Z',
            ccMeasurement: 3500,
        },
        {
            id: 'HvtozDeCx',
            title: 'Toyota RAV 4',
            imageUrl: 'https://media.autochek.africa/file/hjP2msPf.webp',
            year: 2012,
            city: 'Ogba',
            state: 'Lagos',
            gradeScore: 4.300000190734863,
            sellingCondition: 'foreign',
            hasWarranty: false,
            marketplacePrice: 7915000,
            marketplaceOldPrice: 7915000,
            hasFinancing: true,
            mileage: 123321,
            mileageUnit: 'miles',
            installment: 354921,
            depositReceived: false,
            loanValue: 6319124,
            websiteUrl: 'https://autochek.africa/ng/car/rav-4-toyota-ref-HvtozDeCx',
            stats: {
                webViewCount: 0,
                webViewerCount: 0,
                interestCount: 0,
                testDriveCount: 0,
                appViewCount: 0,
                appViewerCount: 0,
                processedLoanCount: 0,
            },
            bodyTypeId: '3',
            sold: false,
            hasThreeDImage: false,
            transmission: 'automatic',
            fuelType: 'petrol',
            marketplaceVisibleDate: '2023-10-26T22:18:48.119Z',
            ccMeasurement: 2700,
        },
        {
            id: 'oZTMf6ovO',
            title: 'Toyota Corolla',
            imageUrl: 'https://media.autochek.africa/file/X4dMDbHi.webp',
            year: 2009,
            city: 'Gwarinpa',
            state: 'Abuja',
            gradeScore: 2.200000047683716,
            sellingCondition: 'foreign',
            hasWarranty: false,
            marketplacePrice: 7015000,
            marketplaceOldPrice: 9015000,
            hasFinancing: true,
            mileage: 2000,
            mileageUnit: 'miles',
            installment: 327393,
            depositReceived: false,
            loanValue: 5822603,
            websiteUrl: 'https://autochek.africa/ng/car/corolla-toyota-ref-oZTMf6ovO',
            stats: {
                webViewCount: 0,
                webViewerCount: 0,
                interestCount: 0,
                testDriveCount: 0,
                appViewCount: 0,
                appViewerCount: 0,
                processedLoanCount: 0,
            },
            bodyTypeId: '8',
            sold: false,
            hasThreeDImage: false,
            transmission: 'automatic',
            fuelType: 'petrol',
            marketplaceVisibleDate: '2023-10-27T06:28:37.699Z',
            ccMeasurement: 2,
        },
        {
            id: 'L9rrIm-KS',
            title: 'Toyota Camry',
            imageUrl: 'https://media.autochek.africa/file/HryPP88w.webp',
            year: 2012,
            city: 'Jahi',
            state: 'Abuja',
            gradeScore: 4,
            sellingCondition: 'foreign',
            hasWarranty: false,
            marketplacePrice: 9315000,
            marketplaceOldPrice: 9415000,
            hasFinancing: true,
            mileage: 67453,
            mileageUnit: 'miles',
            installment: 444189,
            depositReceived: false,
            loanValue: 8016117,
            websiteUrl: 'https://autochek.africa/ng/car/camry-toyota-ref-L9rrIm-KS',
            stats: {
                webViewCount: 0,
                webViewerCount: 0,
                interestCount: 0,
                testDriveCount: 0,
                appViewCount: 0,
                appViewerCount: 0,
                processedLoanCount: 0,
            },
            bodyTypeId: '8',
            sold: false,
            hasThreeDImage: false,
            transmission: 'automatic',
            fuelType: 'petrol',
            marketplaceVisibleDate: '2023-10-27T16:36:23.961Z',
            ccMeasurement: 2,
        },
        {
            id: 'Zi79Opn46',
            title: 'Lexus RX 350',
            imageUrl: 'https://media.autochek.africa/file/ynW16JvZ.webp',
            year: 2007,
            city: 'Gbagada',
            state: 'Lagos',
            gradeScore: 4.400000095367432,
            sellingCondition: 'foreign',
            hasWarranty: false,
            marketplacePrice: 8015000,
            marketplaceOldPrice: 7865000,
            hasFinancing: true,
            mileage: 110510,
            mileageUnit: 'miles',
            installment: 352890,
            depositReceived: false,
            loanValue: 6281495,
            websiteUrl: 'https://autochek.africa/ng/car/rx-350-lexus-ref-Zi79Opn46',
            stats: {
                webViewCount: 0,
                webViewerCount: 0,
                interestCount: 0,
                testDriveCount: 0,
                appViewCount: 0,
                appViewerCount: 0,
                processedLoanCount: 0,
            },
            bodyTypeId: '3',
            sold: false,
            hasThreeDImage: false,
            transmission: 'automatic',
            fuelType: 'petrol',
            marketplaceVisibleDate: '2023-10-27T07:20:33.082Z',
            ccMeasurement: 3500,
        },
        {
            id: 'G5wcokw_-',
            title: 'Toyota RAV 4',
            imageUrl: 'https://media.autochek.africa/file/kciiSijk.webp',
            year: 2012,
            city: 'Isolo',
            state: 'Lagos',
            gradeScore: 4.199999809265137,
            sellingCondition: 'foreign',
            hasWarranty: false,
            marketplacePrice: 8815000,
            marketplaceOldPrice: 8815000,
            hasFinancing: true,
            mileage: 198033,
            mileageUnit: 'miles',
            installment: 391471,
            depositReceived: false,
            loanValue: 6996443,
            websiteUrl: 'https://autochek.africa/ng/car/rav-4-toyota-ref-G5wcokw_-',
            stats: {
                webViewCount: 0,
                webViewerCount: 0,
                interestCount: 0,
                testDriveCount: 0,
                appViewCount: 0,
                appViewerCount: 0,
                processedLoanCount: 0,
            },
            bodyTypeId: '3',
            sold: false,
            hasThreeDImage: false,
            transmission: 'automatic',
            fuelType: 'petrol',
            marketplaceVisibleDate: '2023-10-26T09:19:41.260Z',
            ccMeasurement: 3500,
        },
        {
            id: 'CJE_q_o6z',
            title: 'Toyota RAV 4',
            imageUrl: 'https://media.autochek.africa/file/laohGm3G.webp',
            year: 2012,
            city: 'Okota',
            state: 'Lagos',
            gradeScore: 4.300000190734863,
            sellingCondition: 'foreign',
            hasWarranty: false,
            marketplacePrice: 7865000,
            marketplaceOldPrice: 7865000,
            hasFinancing: true,
            mileage: 65662,
            mileageUnit: 'miles',
            installment: 352890,
            depositReceived: false,
            loanValue: 6281495,
            websiteUrl: 'https://autochek.africa/ng/car/rav-4-toyota-ref-CJE_q_o6z',
            stats: {
                webViewCount: 0,
                webViewerCount: 0,
                interestCount: 0,
                testDriveCount: 0,
                appViewCount: 0,
                appViewerCount: 0,
                processedLoanCount: 0,
            },
            bodyTypeId: '3',
            sold: false,
            hasThreeDImage: false,
            transmission: 'automatic',
            fuelType: 'petrol',
            marketplaceVisibleDate: '2023-10-26T09:19:27.987Z',
            ccMeasurement: 2700,
        },
        {
            id: 'LRcZkW4Pc',
            title: 'Toyota Camry',
            imageUrl: 'https://media.autochek.africa/file/3R7euSgQ.webp',
            year: 2007,
            city: 'Mushin',
            state: 'Lagos',
            gradeScore: 0,
            sellingCondition: 'foreign',
            hasWarranty: false,
            marketplacePrice: 6015000,
            marketplaceOldPrice: 615000,
            hasFinancing: true,
            mileage: 102338,
            mileageUnit: 'miles',
            installment: 285496,
            depositReceived: false,
            loanValue: 5044253,
            websiteUrl: 'https://autochek.africa/ng/car/camry-toyota-ref-LRcZkW4Pc',
            stats: {
                webViewCount: 0,
                webViewerCount: 0,
                interestCount: 0,
                testDriveCount: 0,
                appViewCount: 0,
                appViewerCount: 0,
                processedLoanCount: 0,
            },
            bodyTypeId: '8',
            sold: false,
            hasThreeDImage: false,
            transmission: 'automatic',
            fuelType: 'petrol',
            marketplaceVisibleDate: '2023-10-26T10:21:31.961Z',
            ccMeasurement: 2500,
        },
        {
            id: 'Y8YDSqwda',
            title: 'Lexus ES 350',
            imageUrl: 'https://media.autochek.africa/file/8p2V6RmV.webp',
            year: 2013,
            city: 'Gwarinpa',
            state: 'Abuja',
            gradeScore: 4.400000095367432,
            sellingCondition: 'foreign',
            hasWarranty: false,
            marketplacePrice: 15315000,
            marketplaceOldPrice: 9315000,
            hasFinancing: true,
            mileage: 82707,
            mileageUnit: 'miles',
            installment: 616049,
            depositReceived: false,
            loanValue: 11098763,
            websiteUrl: 'https://autochek.africa/ng/car/es-350-lexus-ref-Y8YDSqwda',
            stats: {
                webViewCount: 0,
                webViewerCount: 0,
                interestCount: 0,
                testDriveCount: 0,
                appViewCount: 0,
                appViewerCount: 0,
                processedLoanCount: 0,
            },
            bodyTypeId: '8',
            sold: false,
            hasThreeDImage: false,
            transmission: 'automatic',
            fuelType: 'petrol',
            marketplaceVisibleDate: '2023-10-25T13:59:35.436Z',
            ccMeasurement: 2,
        },
        {
            id: '8ucX091gl',
            title: 'Toyota Hilux',
            imageUrl: 'https://media.autochek.africa/file/fSwRRLBv.webp',
            year: 2023,
            city: 'Rumuomasi',
            state: 'Port Harcourt',
            gradeScore: 4.800000190734863,
            sellingCondition: 'new',
            hasWarranty: false,
            marketplacePrice: 92165000,
            marketplaceOldPrice: 92165000,
            hasFinancing: true,
            mileage: 10000,
            mileageUnit: 'km',
            installment: 4064622,
            depositReceived: false,
            loanValue: 75499040,
            websiteUrl: 'https://autochek.africa/ng/car/hilux-toyota-ref-8ucX091gl',
            stats: {
                webViewCount: 0,
                webViewerCount: 0,
                interestCount: 0,
                testDriveCount: 0,
                appViewCount: 0,
                appViewerCount: 0,
                processedLoanCount: 0,
            },
            bodyTypeId: '1',
            sold: false,
            hasThreeDImage: false,
            transmission: 'automatic',
            fuelType: 'diesel',
            marketplaceVisibleDate: '2023-10-27T11:52:26.491Z',
        },
        {
            id: 'bOpxtOSn4',
            title: 'Lexus LX 570',
            imageUrl: 'https://media.autochek.africa/file/QyjGv8sp.webp',
            year: 2017,
            city: 'Lekki',
            state: 'Lekki,Lagos',
            gradeScore: 4,
            sellingCondition: 'foreign',
            hasWarranty: false,
            marketplacePrice: 80030000,
            marketplaceOldPrice: 80030000,
            hasFinancing: true,
            mileage: 29115,
            mileageUnit: 'miles',
            installment: 3507761,
            depositReceived: false,
            loanValue: 64892784,
            websiteUrl: 'https://autochek.africa/ng/car/lx-570-lexus-ref-bOpxtOSn4',
            stats: {
                webViewCount: 0,
                webViewerCount: 0,
                interestCount: 0,
                testDriveCount: 0,
                appViewCount: 0,
                appViewerCount: 0,
                processedLoanCount: 0,
            },
            bodyTypeId: '3',
            sold: false,
            hasThreeDImage: false,
            licensePlate: 'not registered',
            transmission: 'automatic',
            fuelType: 'petrol',
            marketplaceVisibleDate: '2023-10-26T20:15:21.766Z',
        },
        {
            id: 'FtvWCc1ji',
            title: 'Toyota Camry',
            imageUrl: 'https://media.autochek.africa/file/xZ4mGqRn.webp',
            year: 2014,
            city: 'Sabo',
            state: 'Lagos',
            gradeScore: 4.199999809265137,
            sellingCondition: 'foreign',
            hasWarranty: false,
            marketplacePrice: 7815000,
            marketplaceOldPrice: 7815000,
            hasFinancing: true,
            mileage: 148000,
            mileageUnit: 'miles',
            installment: 374996,
            depositReceived: false,
            loanValue: 6727530,
            websiteUrl: 'https://autochek.africa/ng/car/camry-toyota-ref-FtvWCc1ji',
            stats: {
                webViewCount: 0,
                webViewerCount: 0,
                interestCount: 0,
                testDriveCount: 0,
                appViewCount: 0,
                appViewerCount: 0,
                processedLoanCount: 0,
            },
            bodyTypeId: '8',
            sold: false,
            hasThreeDImage: false,
            transmission: 'automatic',
            fuelType: 'petrol',
            marketplaceVisibleDate: '2023-10-25T09:32:30.370Z',
        },
        {
            id: '516NP4k2-',
            title: 'Mercedes-Benz ML 350',
            imageUrl: 'https://media.autochek.africa/file/paD9fQaq.webp',
            year: 2012,
            city: 'Ikeja',
            state: 'Lagos',
            gradeScore: 4,
            sellingCondition: 'foreign',
            hasWarranty: false,
            marketplacePrice: 14015000,
            marketplaceOldPrice: 14515000,
            hasFinancing: true,
            mileage: 155285,
            mileageUnit: 'miles',
            installment: 592038,
            depositReceived: false,
            loanValue: 10599794,
            websiteUrl: 'https://autochek.africa/ng/car/ml-350-mercedes-benz-ref-516NP4k2-',
            stats: {
                webViewCount: 0,
                webViewerCount: 0,
                interestCount: 0,
                testDriveCount: 0,
                appViewCount: 0,
                appViewerCount: 0,
                processedLoanCount: 0,
            },
            bodyTypeId: '3',
            sold: false,
            hasThreeDImage: false,
            transmission: 'automatic',
            fuelType: 'petrol',
            marketplaceVisibleDate: '2023-10-25T09:08:46.130Z',
            ccMeasurement: 3500,
        },
        {
            id: 's-AptjGVo',
            title: 'Lexus ES 350',
            imageUrl: 'https://media.autochek.africa/file/0glfRhDz.webp',
            year: 2011,
            city: 'Abule Egba',
            state: 'Lagos',
            gradeScore: 4.400000095367432,
            sellingCondition: 'foreign',
            hasWarranty: false,
            marketplacePrice: 8315000,
            marketplaceOldPrice: 8315000,
            hasFinancing: true,
            mileage: 154522,
            mileageUnit: 'miles',
            installment: 349777,
            depositReceived: false,
            loanValue: 6191546,
            websiteUrl: 'https://autochek.africa/ng/car/es-350-lexus-ref-s-AptjGVo',
            stats: {
                webViewCount: 0,
                webViewerCount: 0,
                interestCount: 0,
                testDriveCount: 0,
                appViewCount: 0,
                appViewerCount: 0,
                processedLoanCount: 0,
            },
            bodyTypeId: '8',
            sold: false,
            hasThreeDImage: false,
            transmission: 'automatic',
            fuelType: 'petrol',
            marketplaceVisibleDate: '2023-10-25T08:50:38.520Z',
            ccMeasurement: 3500,
        },
        {
            id: 'z0GqWAdx_',
            title: 'Toyota Camry',
            imageUrl: 'https://media.autochek.africa/file/Zu8D1WuH.webp',
            year: 2014,
            city: 'Rumukurushi',
            state: 'Port Harcourt',
            gradeScore: 4.400000095367432,
            sellingCondition: 'foreign',
            hasWarranty: false,
            marketplacePrice: 7715000,
            marketplaceOldPrice: 7715000,
            hasFinancing: true,
            mileage: 86000,
            mileageUnit: 'km',
            installment: 370626,
            depositReceived: false,
            loanValue: 6646083,
            websiteUrl: 'https://autochek.africa/ng/car/camry-toyota-ref-z0GqWAdx_',
            stats: {
                webViewCount: 0,
                webViewerCount: 0,
                interestCount: 0,
                testDriveCount: 0,
                appViewCount: 0,
                appViewerCount: 0,
                processedLoanCount: 0,
            },
            bodyTypeId: '8',
            sold: false,
            hasThreeDImage: false,
            transmission: 'automatic',
            fuelType: 'petrol',
            marketplaceVisibleDate: '2023-10-25T06:51:42.943Z',
        },
        {
            id: 'IErW8g7e_',
            title: 'Toyota Highlander',
            imageUrl: 'https://media.autochek.africa/file/tbShzgQv.webp',
            year: 2020,
            city: 'Ikeja',
            state: 'Lagos',
            gradeScore: 4.5,
            sellingCondition: 'foreign',
            hasWarranty: false,
            marketplacePrice: 65015000,
            marketplaceOldPrice: 65015000,
            hasFinancing: true,
            mileage: 18240,
            mileageUnit: 'miles',
            installment: 2877127,
            depositReceived: false,
            loanValue: 53365284,
            websiteUrl: 'https://autochek.africa/ng/car/highlander-toyota-ref-IErW8g7e_',
            stats: {
                webViewCount: 0,
                webViewerCount: 0,
                interestCount: 0,
                testDriveCount: 0,
                appViewCount: 0,
                appViewerCount: 0,
                processedLoanCount: 0,
            },
            bodyTypeId: '3',
            sold: false,
            hasThreeDImage: false,
            transmission: 'automatic',
            fuelType: 'petrol',
            marketplaceVisibleDate: '2023-10-25T06:30:48.787Z',
            ccMeasurement: 3500,
        },
        {
            id: 'iw65o26k3',
            title: 'Lexus GX 460',
            imageUrl: 'https://media.autochek.africa/file/faH9GHZg.webp',
            year: 2022,
            city: 'Ikeja',
            state: 'Lagos',
            gradeScore: 4.5,
            sellingCondition: 'foreign',
            hasWarranty: false,
            marketplacePrice: 85615000,
            marketplaceOldPrice: 85615000,
            hasFinancing: true,
            mileage: 11716,
            mileageUnit: 'miles',
            installment: 3783219,
            depositReceived: false,
            loanValue: 70070720,
            websiteUrl: 'https://autochek.africa/ng/car/gx-460-lexus-ref-iw65o26k3',
            stats: {
                webViewCount: 0,
                webViewerCount: 0,
                interestCount: 0,
                testDriveCount: 0,
                appViewCount: 0,
                appViewerCount: 0,
                processedLoanCount: 0,
            },
            bodyTypeId: '3',
            sold: false,
            hasThreeDImage: false,
            transmission: 'automatic',
            fuelType: 'petrol',
            marketplaceVisibleDate: '2023-10-25T06:30:42.790Z',
            ccMeasurement: 4600,
        },
        {
            id: 'ZwEJYa8kp',
            title: 'Toyota Corolla',
            imageUrl: 'https://media.autochek.africa/file/yuaM3bdu.webp',
            year: 2014,
            city: 'Abule Egba',
            state: 'Lagos',
            gradeScore: 4.400000095367432,
            sellingCondition: 'foreign',
            hasWarranty: false,
            marketplacePrice: 9515000,
            marketplaceOldPrice: 9515000,
            hasFinancing: true,
            mileage: 112354,
            mileageUnit: 'miles',
            installment: 449286,
            depositReceived: false,
            loanValue: 8112123,
            websiteUrl: 'https://autochek.africa/ng/car/corolla-toyota-ref-ZwEJYa8kp',
            stats: {
                webViewCount: 0,
                webViewerCount: 0,
                interestCount: 0,
                testDriveCount: 0,
                appViewCount: 0,
                appViewerCount: 0,
                processedLoanCount: 0,
            },
            bodyTypeId: '8',
            sold: false,
            hasThreeDImage: false,
            transmission: 'automatic',
            fuelType: 'petrol',
            marketplaceVisibleDate: '2023-10-24T21:12:24.223Z',
            ccMeasurement: 1800,
        },
        {
            id: 'qe6mih2ad',
            title: 'Lexus GX 460',
            imageUrl: 'https://media.autochek.africa/file/Wi8AklXG.webp',
            year: 2015,
            city: 'Abule Egba',
            state: 'Lagos',
            gradeScore: 4.300000190734863,
            sellingCondition: 'foreign',
            hasWarranty: false,
            marketplacePrice: 34015000,
            marketplaceOldPrice: 34015000,
            hasFinancing: true,
            mileage: 111660,
            mileageUnit: 'miles',
            installment: 1520669,
            depositReceived: false,
            loanValue: 27891032,
            websiteUrl: 'https://autochek.africa/ng/car/gx-460-lexus-ref-qe6mih2ad',
            stats: {
                webViewCount: 0,
                webViewerCount: 0,
                interestCount: 0,
                testDriveCount: 0,
                appViewCount: 0,
                appViewerCount: 0,
                processedLoanCount: 0,
            },
            bodyTypeId: '3',
            sold: false,
            hasThreeDImage: false,
            transmission: 'automatic',
            fuelType: 'petrol',
            marketplaceVisibleDate: '2023-10-24T20:55:12.545Z',
            ccMeasurement: 4600,
        },
        {
            id: 'VxQUxFdhg',
            title: 'Toyota Corolla',
            imageUrl: 'https://media.autochek.africa/file/oQ1WfrTR.webp',
            year: 2005,
            city: 'Gwarinpa',
            state: 'Abuja',
            gradeScore: 4,
            sellingCondition: 'foreign',
            hasWarranty: false,
            marketplacePrice: 5365000,
            marketplaceOldPrice: 5365000,
            hasFinancing: true,
            mileage: 155325,
            mileageUnit: 'miles',
            installment: 237562,
            depositReceived: false,
            loanValue: 4123505,
            websiteUrl: 'https://autochek.africa/ng/car/corolla-toyota-ref-VxQUxFdhg',
            stats: {
                webViewCount: 0,
                webViewerCount: 0,
                interestCount: 0,
                testDriveCount: 0,
                appViewCount: 0,
                appViewerCount: 0,
                processedLoanCount: 0,
            },
            bodyTypeId: '8',
            sold: false,
            hasThreeDImage: false,
            transmission: 'automatic',
            fuelType: 'petrol',
            marketplaceVisibleDate: '2023-10-24T17:51:44.400Z',
            ccMeasurement: 2,
        },
        {
            id: 'TYlGZCBwe',
            title: 'Toyota Landcruiser Vx V8 ',
            imageUrl: 'https://media.autochek.africa/file/0jlGk3kS.webp',
            year: 2020,
            city: 'Ogba',
            state: 'Lagos',
            gradeScore: 4.5,
            sellingCondition: 'foreign',
            hasWarranty: false,
            marketplacePrice: 71015000,
            marketplaceOldPrice: 71015000,
            hasFinancing: true,
            mileage: 15761,
            mileageUnit: 'km',
            installment: 3146894,
            depositReceived: false,
            loanValue: 58213376,
            websiteUrl: 'https://autochek.africa/ng/car/landcruiser-vx-v8--toyota-ref-TYlGZCBwe',
            stats: {
                webViewCount: 0,
                webViewerCount: 0,
                interestCount: 0,
                testDriveCount: 0,
                appViewCount: 0,
                appViewerCount: 0,
                processedLoanCount: 0,
            },
            bodyTypeId: '3',
            sold: false,
            hasThreeDImage: false,
            transmission: 'automatic',
            fuelType: 'petrol',
            marketplaceVisibleDate: '2023-10-24T17:27:07.793Z',
            ccMeasurement: 5700,
        },
    ],
    pagination: {
        total: 691,
        currentPage: 1,
        pageSize: 24,
    },
};

export const popularCarMakes = {
    makeList: [
        {
            id: 9,
            name: 'Audi',
            imageUrl: 'https://storage.googleapis.com/img.autochek.africa/marketplace/audi.png',
        },
        {
            id: 13,
            name: 'BMW',
            imageUrl: 'https://storage.googleapis.com/img.autochek.africa/brands/bmw.svg',
        },
        {
            id: 45,
            name: 'Honda',
            imageUrl: 'https://storage.googleapis.com/img.autochek.africa/brands/honda.svg',
        },
        {
            id: 47,
            name: 'Hyundai',
            imageUrl: 'https://storage.googleapis.com/img.autochek.africa/brands/hyundai.svg',
        },
        {
            id: 51,
            name: 'Jaguar',
            imageUrl: 'https://storage.googleapis.com/img.autochek.africa/marketplace/jaguar.jpg',
        },
        {
            id: 59,
            name: 'Land Rover',
            imageUrl:
                'https://storage.googleapis.com/img.autochek.africa/marketplace/land-rover.png',
        },
        {
            id: 61,
            name: 'Lexus',
            imageUrl: 'https://storage.googleapis.com/img.autochek.africa/brands/lexus.svg',
        },
        {
            id: 70,
            name: 'Mercedes-Benz',
            imageUrl: 'https://storage.googleapis.com/img.autochek.africa/brands/benz.svg',
        },
        {
            id: 76,
            name: 'Nissan',
            imageUrl: 'https://storage.googleapis.com/img.autochek.africa/brands/nissan.svg',
        },
        {
            id: 106,
            name: 'Toyota',
            imageUrl: 'https://storage.googleapis.com/img.autochek.africa/marketplace/toyota.png',
        },
        {
            id: 110,
            name: 'Volkswagen',
            imageUrl: 'https://storage.googleapis.com/img.autochek.africa/brands/volkswagen.svg',
        },
    ],
    pagination: {
        total: 11,
        currentPage: 1,
        pageSize: 20,
    },
};
